# Generated by Django 4.0.4 on 2022-06-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0010_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='facebook_url',
            field=models.CharField(default='facebook.com/', max_length=60),
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='blog/images/usuarios'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram_url',
            field=models.CharField(default='https://www.instagram.com/', max_length=60),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='perfil',
            name='twitter_url',
            field=models.CharField(default='https://twitter.com/', max_length=60),
        ),
    ]
