# Generated by Django 4.0.4 on 2022-07-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0011_perfil_facebook_url_perfil_imagen_perfil_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='facebook_url',
            field=models.CharField(default='https://www.facebook.com/', max_length=60, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/images/usuarios'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='instagram_url',
            field=models.CharField(default='https://www.instagram.com/', max_length=60, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=60, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='twitter_url',
            field=models.CharField(default='https://www.twitter.com/', max_length=60, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
