# Generated by Django 4.0.4 on 2022-07-02 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paramiko.pkey


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0015_remove_comentarios_nombre_comentarios_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(default=paramiko.pkey.PKey, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
