# Generated by Django 4.0.4 on 2022-07-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0012_alter_categoria_nome_alter_perfil_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/usuarios'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
